
name: haskelleene
version: 0.1.0.0
synopsis: Haskelleene, Implementing Finite Automata and Regular Expressions
description: See haskelleene.pdf
maintainer: Liam Chung <lwalkerchung@gmail.com>
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck

library:
  source-dirs: lib
  exposed-modules:
    - Alphabet
    - Automata
    - Examples
    - Kleene
    - Regex
  dependencies:
    - containers
    - QuickCheck
  #   - mtl

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - haskelleene

tests:
  simpletests:
    main: simpletests.lhs
    source-dirs: test
    dependencies:
      - haskelleene
      - QuickCheck
      - hspec
